monitors:
  - interface: "eth0"
    interval: 5
    ports: [80, 443]
  - interface: "lo"
    interval: 10
    ports: []

writers:
  path: "./"
  format: "csv"  # 可选：csv, txt, log
  interval_type: "day"  # 可选：week, day, hour

observers:
  enabled: true
  cleanup_days: 30  # 清理30天前的文件